#!/usr/bin/env bash

echo "Waiting for emulator to start..."

# Returns a symbol for the adb getprop result
# to use it for the wait output
function waitsymbol {
	if [[ $1 =~ "device offline" ]]; then
		echo -n "o"
	elif [[ $1 =~ "running" ]]; then
		echo -n "r"
	else
		#Unknown output
		echo -n "."
	fi
}

bootanim=""
failcounter=0
until [[ "$bootanim" =~ "stopped" ]]; do
   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
   if [[ "$bootanim" =~ "not found" ]]; then
      let "failcounter += 1"
      if [[ $failcounter -gt 20 ]]; then
        echo "  Failed to start emulator"
        exit 1
      fi
   fi
   waitsymbol $bootanim
   sleep 1
done
